# permissions for end users to edit certs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-editor-role
rules:
- apiGroups:
  - cert.injector.ko
  resources:
  - certs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert.injector.ko
  resources:
  - certs/status
  verbs:
  - get
