apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    cert.injector/inject: "true"
    cert.injector/secret: "injector-tls"
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
