image:
  repository: ghcr.io/onmetal/cert-injector
  tag: 0.3.0
  pullPolicy: IfNotPresent

resources:
#  limits:
#    cpu: 100m
#    memory: 30Mi
  requests:
    cpu: 100m
    memory: 20Mi

service:
  name: cert-injector
  port: 443

certissuer:
  image:
    repository: ghcr.io/onmetal/cert-issuer
    tag: 0.3.0
    pullPolicy: IfNotPresent

  resolver:
    image: ghcr.io/onmetal/acmeresolver:0.3.0
  resources:
    #  limits:
    #    cpu: 100m
    #    memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi
