image:
  repository: yotsyni/cert-injector
  tag: 0.2.1
  pullPolicy: IfNotPresent

resources:
#  limits:
#    cpu: 100m
#    memory: 30Mi
  requests:
    cpu: 100m
    memory: 20Mi

service:
  name: cert-injector
  port: 443

certissuer:
  image:
    repository: yotsyni/cert-issuer
    tag: 0.2.1
    pullPolicy: IfNotPresent

  resolver:
    image: yotsyni/acmeresolver:0.2.1
  resources:
    #  limits:
    #    cpu: 100m
    #    memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi
