apiVersion: v1
kind: Service
metadata:
  name: injector
  annotations:
    cert.injector.ko/ca-url: https://acme-v02.api.letsencrypt.org/directory
    cert.injector.ko/domains: "example.domain.com"
    cert.injector.ko/email: your@email.com
    cert.injector.ko/inject: "true"
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: nginx