apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certissuer-cluster-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
    verbs:
      - create
      - update
      - delete
      - patch
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - update
      - get
      - list
      - patch
      - watch