apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: machine-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: certissuer-cluster-role
subjects:
  - kind: ServiceAccount
    name: certissuer
    namespace: {{ .Release.Namespace }}