apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: certissuer-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: certissuer-election
subjects:
- kind: ServiceAccount
  name: certissuer
  namespace: {{ .Release.Namespace }}
