name: Lint - Helm

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    name: Lint Chart

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v3.1

      - uses: actions/setup-python@v4
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1
        with:
          version: v3.4.0

      - name: Run chart lint
        id: lint
        run: ct lint deploy/helm/injector
