name: Release - Helm

on:
  push:
    tags:
      - v*
    paths:
      - 'deploy/**'
      - '.github/workflows/helm-publish.yaml'
      - '!**.md'
  workflow_dispatch:

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    name: Lint Chart

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v2.1

      - uses: actions/setup-python@v3
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.0
        with:
          version: v3.4.0

      - name: Run chart lint
        id: lint
        run: ct lint deploy/helm/injector

  publish-chart:
    runs-on: self-hosted
    name: Publish Chart
    needs: lint-chart

    steps:
      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          keep_files: true

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: deploy/helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_SKIP_EXISTING: true
